[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "php artisan migrate --force",
  "php artisan config:clear",
  "php artisan route:clear"
]

[start]
cmd = "php -d upload_max_filesize=100M -d post_max_size=105M -d memory_limit=256M -S 0.0.0.0:$PORT -t public public/index.php"
