<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class KewenanganProvinsi extends Model
{
    use HasFactory;

    protected $table = 'kewenangan_provinsi';
    
    protected $fillable = [
        'Nama_Lembaga_Yayasan',
        'status',
        'kabupaten_kota',
        'alamat',
        'ketua_yayasan',
        'no',
        'nama_lks',
        'pusat_cabang',
        'kabupaten_kota_lks',
        'alamat_lks',
        'nama_ketua_lks',
        'nama_sekretaris',
        'nama_bendahara',
        'nama_notaris',
        'nomor_notaris',
        'tanggal_akta',
        'nomor_pengesahan',
        'tanggal_pengesahan',
        'nama_npwp',
        'nomor_npwp',
        'status_bangunan',
        'akreditasi',
        'tanda_pendaftaran_pusat_nama_kab_kota',
        'tanda_pendaftaran_pusat_nomor',
        'tanda_pendaftaran_pusat_tanggal',
        'tanda_pendaftaran_cabang_nama_kab_kota',
        'tanda_pendaftaran_cabang_nomor',
        'tanda_pendaftaran_cabang_tanggal',
        'rekom_dinsos_nomor',
        'rekom_dinsos_tanggal',
        'tanda_pendaftaran_provinsi_nomor',
        'tanda_pendaftaran_provinsi_tanggal',
        'jenis_pelayanan_PPKS',
        'jumlah_seluruh_binaan',
        'jumlah_dalam_panti',
        'jumlah_luar_panti',
        'anak_balita_terlantar_DP',
        'anak_balita_terlantar_LP',
        'anak_terlantar_DP',
        'anak_terlantar_LP',
        'anak_yangberhadapan_dengan_hukum_DP',
        'anak_yangberhadapan_dengan_hukum_LP',
        'anak_jalanan_DP',
        'anak_jalanan_LP',
        'anak_dengan_kedisabilitas_DP',
        'anak_dengan_kedisabilitas_LP',
        'anak_yangmenjadi_tidak_kekerasan_DP',
        'anak_yangmenjadi_tidak_kekerasan_LP',
        'anak_yang_memerlukan_perlindungan_khusus_DP',
        'anak_yang_memerlukan_perlindungan_khusus_LP',
        'lanjut_usia_terlantar_DP',
        'lanjut_usia_terlantar_LP',
        'disabilitas_fisik_DP',
        'disabilitas_fisik_LP',
        'disabilitas_intelektual_DP',
        'disabilitas_intelektual_LP',
        'disabilitas_mental_DP',
        'disabilitas_mental_LP',
        'disabilitas_sensorik_DP',
        'disabilitas_sensorik_LP',
        'tuna_susila_DP',
        'tuna_susila_LP',
        'gelandangan_DP',
        'gelandangan_LP',
        'pengemis_DP',
        'pengemis_LP',
        'pemulung_DP',
        'pemulung_LP',
        'kelompok_minoritas_DP',
        'kelompok_minoritas_LP',
        'BWBLP_DP',
        'BWBLP_LP',
        'orang_dengan_hiv_aids_DP',
        'orang_dengan_hiv_aids_LP',
        'penyalahgunaan_Napza_DP',
        'penyalahgunaan_Napza_LP',
        'korban_Trafficking_DP',
        'korban_Trafficking_LP',
        'korban_tindak_kekerasan_DP',
        'korban_tindak_kekerasan_LP',
        'PMBS_DP',
        'PMBS_LP',
        'korban_bencana_alam_DP',
        'korban_bencana_alam_LP',
        'korban_bencana_sosial_DP',
        'korban_bencana_sosial_LP',
        'perempuan_rawan_sosial_ekonomi_DP',
        'perempuan_rawan_sosial_ekonomi_LP',
        'fakir_miskin_DP',
        'fakir_miskin_LP',
        'keluarga_bermasalah_sosial_psikologis_DP',
        'keluarga_bermasalah_sosial_psikologis_LP',
        'komunitas_adat_terpencil_DP',
        'komunitas_adat_terpencil_LP',
        'nomor_tlp',
        'email',
        'link_tanda_daftar'
    ];

    protected $casts = [
        'tanggal_akta' => 'date',
        'tanggal_pengesahan' => 'date',
        'tanda_pendaftaran_pusat_tanggal' => 'date',
        'tanda_pendaftaran_cabang_tanggal' => 'date',
        'rekom_dinsos_tanggal' => 'date',
        'tanda_pendaftaran_provinsi_tanggal' => 'date',
        'jumlah_seluruh_binaan' => 'integer',
        'jumlah_dalam_panti' => 'integer',
        'jumlah_luar_panti' => 'integer',
        'anak_balita_terlantar_DP' => 'integer',
        'anak_balita_terlantar_LP' => 'integer',
        'anak_terlantar_DP' => 'integer',
        'anak_terlantar_LP' => 'integer',
        'anak_yangberhadapan_dengan_hukum_DP' => 'integer',
        'anak_yangberhadapan_dengan_hukum_LP' => 'integer',
        'anak_jalanan_DP' => 'integer',
        'anak_jalanan_LP' => 'integer',
        'anak_dengan_kedisabilitas_DP' => 'integer',
        'anak_dengan_kedisabilitas_LP' => 'integer',
        'anak_yangmenjadi_tidak_kekerasan_DP' => 'integer',
        'anak_yangmenjadi_tidak_kekerasan_LP' => 'integer',
        'anak_yang_memerlukan_perlindungan_khusus_DP' => 'integer',
        'anak_yang_memerlukan_perlindungan_khusus_LP' => 'integer',
        'lanjut_usia_terlantar_DP' => 'integer',
        'lanjut_usia_terlantar_LP' => 'integer',
        'disabilitas_fisik_DP' => 'integer',
        'disabilitas_fisik_LP' => 'integer',
        'disabilitas_intelektual_DP' => 'integer',
        'disabilitas_intelektual_LP' => 'integer',
        'disabilitas_mental_DP' => 'integer',
        'disabilitas_mental_LP' => 'integer',
        'disabilitas_sensorik_DP' => 'integer',
        'disabilitas_sensorik_LP' => 'integer',
        'tuna_susila_DP' => 'integer',
        'tuna_susila_LP' => 'integer',
        'gelandangan_DP' => 'integer',
        'gelandangan_LP' => 'integer',
        'pengemis_DP' => 'integer',
        'pengemis_LP' => 'integer',
        'pemulung_DP' => 'integer',
        'pemulung_LP' => 'integer',
        'kelompok_minoritas_DP' => 'integer',
        'kelompok_minoritas_LP' => 'integer',
        'BWBLP_DP' => 'integer',
        'BWBLP_LP' => 'integer',
        'orang_dengan_hiv_aids_DP' => 'integer',
        'orang_dengan_hiv_aids_LP' => 'integer',
        'penyalahgunaan_Napza_DP' => 'integer',
        'penyalahgunaan_Napza_LP' => 'integer',
        'korban_Trafficking_DP' => 'integer',
        'korban_Trafficking_LP' => 'integer',
        'korban_tindak_kekerasan_DP' => 'integer',
        'korban_tindak_kekerasan_LP' => 'integer',
        'PMBS_DP' => 'integer',
        'PMBS_LP' => 'integer',
        'korban_bencana_alam_DP' => 'integer',
        'korban_bencana_alam_LP' => 'integer',
        'korban_bencana_sosial_DP' => 'integer',
        'korban_bencana_sosial_LP' => 'integer',
        'perempuan_rawan_sosial_ekonomi_DP' => 'integer',
        'perempuan_rawan_sosial_ekonomi_LP' => 'integer',
        'fakir_miskin_DP' => 'integer',
        'fakir_miskin_LP' => 'integer',
        'keluarga_bermasalah_sosial_psikologis_DP' => 'integer',
        'keluarga_bermasalah_sosial_psikologis_LP' => 'integer',
        'komunitas_adat_terpencil_DP' => 'integer',
        'komunitas_adat_terpencil_LP' => 'integer',
    ];
}
